import { getCurrentProvider, getCurrentModel, geminiConfig, deepseekConfig, type AIProvider } from '@/config/gemini';

// 获取运行时API密钥（优先从localStorage读取）
const getRuntimeAPIKey = (provider: AIProvider): string => {
  const storageKey = provider === 'gemini' ? 'gemini_api_key' : 'deepseek_api_key';
  const storedKey = localStorage.getItem(storageKey);

  if (storedKey) {
    return storedKey;
  }

  // 回退到环境变量
  return provider === 'gemini' ? geminiConfig.apiKey : deepseekConfig.apiKey;
};

// 获取当前选择的提供商（优先从localStorage读取）
const getRuntimeProvider = (): AIProvider => {
  const storedProvider = localStorage.getItem('selected_ai_provider') as AIProvider;
  return storedProvider || getCurrentProvider();
};

// 获取运行时模型（优先从localStorage读取）
const getRuntimeModel = (provider: AIProvider): string => {
  const storageKey = `${provider}_model`;
  const storedModel = localStorage.getItem(storageKey);

  if (storedModel) {
    return storedModel;
  }

  // 回退到环境变量或默认值
  return getCurrentModel(provider);
};

// AI Response interface
export interface AIResponse {
  text: string;
  provider: AIProvider;
}

// Base AI Client interface
interface AIClient {
  generateContent(prompt: string): Promise<string>;
}

// Gemini API Client
class GeminiClient implements AIClient {
  async generateContent(prompt: string): Promise<string> {
    const apiKey = getRuntimeAPIKey('gemini');
    if (!apiKey) {
      throw new Error('Gemini API key not configured');
    }

    const model = getRuntimeModel('gemini');
    const response = await fetch(
      `${geminiConfig.baseUrl}/models/${model}:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }]
        }),
      }
    );

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!text) {
      throw new Error('No content generated by Gemini');
    }
    
    return text;
  }
}

// DeepSeek API Client
class DeepSeekClient implements AIClient {
  async generateContent(prompt: string): Promise<string> {
    const apiKey = getRuntimeAPIKey('deepseek');
    if (!apiKey) {
      throw new Error('DeepSeek API key not configured');
    }

    const model = getRuntimeModel('deepseek');
    const response = await fetch(`${deepseekConfig.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: model,
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 4000,
        stream: false
      }),
    });

    if (!response.ok) {
      throw new Error(`DeepSeek API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    const text = data.choices?.[0]?.message?.content;
    
    if (!text) {
      throw new Error('No content generated by DeepSeek');
    }
    
    return text;
  }
}

// AI Client Factory
class AIClientFactory {
  private static geminiClient = new GeminiClient();
  private static deepseekClient = new DeepSeekClient();

  static getClient(provider?: AIProvider): AIClient {
    const currentProvider = provider || getCurrentProvider();
    
    switch (currentProvider) {
      case 'deepseek':
        return this.deepseekClient;
      case 'gemini':
      default:
        return this.geminiClient;
    }
  }
}

// Main function to generate word data
export const generateWordData = async (word: string, provider?: AIProvider): Promise<AIResponse> => {
  const currentProvider = provider || getRuntimeProvider();
  const client = AIClientFactory.getClient(currentProvider);
  
  const prompt = `请为英语单词"${word}"生成完整的学习信息，以JSON格式返回，包含以下字段：
{
  "word": "${word}",
  "pronunciation": "音标，如/wɜːrd/",
  "partOfSpeech": "词性，如n.",
  "meaning": "中文含义",
  "frequency": "high/medium/low之一",
  "frequencyNote": "使用场景说明",
  "vowels": [
    {
      "vowel": "主要元音字母",
      "sound": "音标发音",
      "similarWords": [
        {
          "word": "同音规律单词1",
          "pronunciation": "音标",
          "meaning": "简单中文翻译"
        },
        {
          "word": "同音规律单词2",
          "pronunciation": "音标",
          "meaning": "简单中文翻译"
        },
        {
          "word": "同音规律单词3",
          "pronunciation": "音标",
          "meaning": "简单中文翻译"
        }
      ]
    }
  ],
  "etymology": {
    "root": "词根",
    "affix": "词缀",
    "coreMeaning": "核心含义",
    "changeMeaning": "变化含义", 
    "finalMeaning": "最终解释"
  },
  "collocations": [
    {
      "phrase": "常用搭配",
      "meaning": "搭配含义",
      "context": "使用语境"
    }
  ],
  "exampleSentences": [
    {
      "sentence": "包含该单词的完整英文例句",
      "translation": "该例句的中文翻译"
    },
    {
      "sentence": "第二个例句",
      "translation": "第二个例句的翻译"
    }
  ]
}

注意：
1. similarWords数组中每个单词都要有word、pronunciation和meaning三个字段
2. meaning字段应该是简单的中文翻译，1-3个汉字即可，如"书"、"猫"、"工作"等
3. 同音词、常用搭配和例句各提供2-3个即可，不要太多
4. 确保所有单词的pronunciation都是准确的音标格式
5. 选择的同音词应该是常见的基础词汇，便于学习记忆

请确保返回的是有效的JSON格式，不要包含其他文字说明。`;

  try {
    const text = await client.generateContent(prompt);
    return {
      text,
      provider: currentProvider
    };
  } catch (error) {
    console.error(`${currentProvider} API error:`, error);
    throw error;
  }
};

// Utility function to check if API is configured
export const isAIConfigured = (provider?: AIProvider): boolean => {
  const currentProvider = provider || getRuntimeProvider();
  const apiKey = getRuntimeAPIKey(currentProvider);

  // 基本检查
  if (!apiKey || apiKey === '' || apiKey.includes('your_') || apiKey.includes('_here')) {
    return false;
  }

  // 提供商特定的格式检查
  if (currentProvider === 'gemini') {
    // Gemini API密钥通常以AIza开头
    return apiKey.startsWith('AIza') && apiKey.length > 20;
  } else if (currentProvider === 'deepseek') {
    // DeepSeek API密钥通常以sk-开头
    return apiKey.startsWith('sk-') && apiKey.length > 20;
  }

  // 默认检查
  return apiKey.length > 10;
};

// Get available providers
export const getAvailableProviders = (): AIProvider[] => {
  const providers: AIProvider[] = [];
  
  if (isAIConfigured('gemini')) {
    providers.push('gemini');
  }
  
  if (isAIConfigured('deepseek')) {
    providers.push('deepseek');
  }
  
  return providers;
};
