
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { word } = await req.json();
    
    if (!word) {
      return new Response(
        JSON.stringify({ error: 'Word is required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) {
      return new Response(
        JSON.stringify({ error: 'Gemini API key not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create Supabase client with service role
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Check if word already exists
    const { data: existingWord } = await supabase
      .from('words')
      .select('*')
      .eq('word', word.toLowerCase())
      .single();

    if (existingWord) {
      return new Response(
        JSON.stringify({ wordData: existingWord }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Generate word data using Gemini - 修正API端点
    const prompt = `请为英语单词"${word}"生成完整的学习信息，以JSON格式返回，包含以下字段：
    {
      "word": "${word}",
      "pronunciation": "音标，如/wɜːrd/",
      "partOfSpeech": "词性，如n.",
      "meaning": "中文含义",
      "frequency": "high/medium/low之一",
      "frequencyNote": "使用场景说明",
      "vowels": [
        {
          "vowel": "主要元音字母",
          "sound": "音标发音",
          "similarWords": ["3-5个同音规律的单词"]
        }
      ],
      "etymology": {
        "root": "词根",
        "affix": "词缀",
        "coreMeaning": "核心含义",
        "changeMeaning": "变化含义", 
        "finalMeaning": "最终解释"
      },
      "collocations": [
        {
          "phrase": "常用搭配",
          "meaning": "搭配含义",
          "context": "使用语境"
        }
      ]
    }
    
    请确保返回的是有效的JSON格式，不要包含其他文字说明。`;

    // 使用正确的Gemini API端点
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${geminiApiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }]
      }),
    });

    if (!response.ok) {
      console.error(`Gemini API error: ${response.status} ${response.statusText}`);
      const errorText = await response.text();
      console.error('Gemini API error response:', errorText);
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
    }

    const geminiData = await response.json();
    console.log('Gemini API response:', geminiData);
    
    const generatedText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      console.error('No content generated by Gemini:', geminiData);
      throw new Error('No content generated by Gemini');
    }

    // Parse the JSON response from Gemini
    let wordData;
    try {
      const cleanedText = generatedText.replace(/```json\n?|\n?```/g, '').trim();
      wordData = JSON.parse(cleanedText);
    } catch (parseError) {
      console.error('Failed to parse Gemini response:', generatedText);
      throw new Error('Failed to parse AI response');
    }

    // Store in database
    const { data: savedWord, error: saveError } = await supabase
      .from('words')
      .insert([{
        word: wordData.word.toLowerCase(),
        pronunciation: wordData.pronunciation,
        part_of_speech: wordData.partOfSpeech,
        meaning: wordData.meaning,
        frequency: wordData.frequency,
        frequency_note: wordData.frequencyNote,
        vowels: wordData.vowels,
        etymology: wordData.etymology,
        collocations: wordData.collocations
      }])
      .select()
      .single();

    if (saveError) {
      console.error('Error saving word:', saveError);
      // Return generated data even if save fails
      return new Response(
        JSON.stringify({ wordData }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ wordData: savedWord }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-word-data function:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
