// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufxvhcpcaqvqharbabzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmeHZoY3BjYXF2cWhhcmJhYnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODg4NTMsImV4cCI6MjA2NTQ2NDg1M30.spPvrd3tdidrZe2Z4lDsRwZUIOa2BqSaFVmWnA03AJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);